=== ARLM-Keller/wide-language-index/index/sample.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Language sample",
    "description": "An audio sample tagged as containing a language of interest. It describes the sample's language, where it can be downloaded from, and its provenance.",
	"type": "object",
	"properties": {
		"language": {"type": "string"},
		"title": {"type": "string"},
		"source_name": {"type": "string"},
		"source_url": {"type": "string"},
		"media_urls": {
			"type": "array",
			"items": {
				"type": "string",
				"minItems": 1,
				"uniqueItems": true
			}
		},
		"checksum": {"type": "string"},
		"origin_checksum": {"type": "string"},
		"pregain": {"type": "string"},
		"date": {"type": "string"},
		"annotations": {
            "type": "array",
            "items": {"$ref": "annotation.schema.json"}
		}
	},
	"required": [
		"language",
		"title",
		"source_name",
		"source_url",
		"media_urls",
		"date",
		"checksum"
	]
}

=== ARLM-Keller/wide-language-index/index/ukr/ukr-c7ecffba80b294405a845ccb216faa60.json
{
  "annotations": [
    {
      "annotator": "Lars Yencken <lars@yencken.org>",
      "date": "2015-11-15",
      "duration": 20,
      "genders": "female",
      "label": "good",
      "offset": 480,
      "problems": [],
      "speakers": 1
    }
  ],
  "checksum": "c7ecffba80b294405a845ccb216faa60",
  "date": "2009-08-01",
  "language": "ukr",
  "media_urls": [
    "http://www.archive.org/download/human_rights_02_0908_librivox/human_rights_un_ukr_r90.mp3",
    "http://mirror.widelanguageindex.org/ukr/ukr-c7ecffba80b294405a845ccb216faa60.mp3"
  ],
  "source_name": "United Nations",
  "source_url": "https://librivox.org/universal-declaration-of-human-rights-by-united-nations-volume-02/",
  "title": "Universal Declaration of Human Rights"
}

=== ARLM-Keller/wide-language-index/index/kor/kor-6fba79ed6e621fd5aeaaed0cfd05545f.json
{
  "checksum": "6fba79ed6e621fd5aeaaed0cfd05545f", 
  "date": "2015-03-23", 
  "language": "kor", 
  "media_urls": [
    "http://av.voanews.com/clips/VKO/2015/03/23/20150323-120000-VKO-program.mp3", 
    "http://mirror.widelanguageindex.org/kor/kor-6fba79ed6e621fd5aeaaed0cfd05545f.mp3"
  ], 
  "source_name": "VOA \ub274\uc2a4 \ud22c\ub370\uc774 - Voice of America", 
  "source_url": "http://www.voakorea.com/audio/2672561.html", 
  "title": "VOA \ub274\uc2a4 \ud22c\ub370\uc774 2\ubd80 - 3\uc6d4 23, 2015"
}

=== ARLM-Keller/wide-language-index/index/rus/rus-3849265e19b50c56f2ee7db06de84316.json
{
  "checksum": "3849265e19b50c56f2ee7db06de84316",
  "date": "2015-03-23",
  "language": "rus",
  "media_urls": [
    "http://feedproxy.google.com/~r/russian/~3/wrMOFnc-4gw/russian_150323_400086.mp3"
  ],
  "source_name": "SBS Russian",
  "source_url": "http://feedproxy.google.com/~r/russian/~3/wrMOFnc-4gw/russian_150323_400086.mp3",
  "title": "Clock ticks on time zone change in SA"
}

=== ARLM-Keller/wide-language-index/index/hin/hin-f704ddcc250ea657fdae7efec3ad0dbd.json
{
  "checksum": "f704ddcc250ea657fdae7efec3ad0dbd",
  "date": "2015-03-21",
  "language": "hin",
  "media_urls": [
    "http://feedproxy.google.com/~r/sbshindi/~3/Y8006OsRi4k/hindi_150321_399822.mp3",
    "http://mirror.widelanguageindex.org/hin/hin-f704ddcc250ea657fdae7efec3ad0dbd.mp3"
  ],
  "source_name": "SBS Hindi",
  "source_url": "http://feedproxy.google.com/~r/sbshindi/~3/Y8006OsRi4k/hindi_150321_399822.mp3",
  "title": "DK Ravi's death - Was it a suicide or was he murdered?"
}

=== ARLM-Keller/wide-language-index/index/amh/amh-86e30571e404651abe353aec868e2389.json
{
  "checksum": "86e30571e404651abe353aec868e2389",
  "date": "2015-03-21",
  "language": "amh",
  "media_urls": [
    "http://av.voanews.com/clips/VAM/2015/03/21/20150321-180000-VAM-program.mp3",
    "http://mirror.widelanguageindex.org/amh/amh-86e30571e404651abe353aec868e2389.mp3"
  ],
  "source_name": "ከምሽቱ ሦስት ሰዓት የአማርኛ ዜና - የአሜሪካ ድምፅ",
  "source_url": "http://amharic.voanews.com/audio/2670994.html",
  "title": "ከምሽቱ ሦስት ሰዓት የአማርኛ ዜና - ማርች 21, 2015"
}

=== ARLM-Keller/wide-language-index/index/tel/tel-be78d9c871b70e859ce3e78bf0ff07da.json
{
  "checksum": "be78d9c871b70e859ce3e78bf0ff07da",
  "date": "2012-06-23",
  "language": "tel",
  "media_urls": [
    "http://www.thehindu.com/multimedia/archive/01131/TeluguDisasterEdit_1131647a.mp3"
  ],
  "source_name": "The Hindu: Podcasts in Telugu",
  "source_url": "http://www.thehindu.com/opinion/editorial/article3595284.ece?ref=audio",
  "title": "Disaster ahoy! [Telugu: Onchi unna vipaththu] Editorial, June 23, 2012. Translated by V.R. Subrahmanyam, presented by Srinivas Ghantasala"
}

=== ARLM-Keller/wide-language-index/index/ron/ron-09ec515e8daa6e5b914df85abb3618df.json
{
  "checksum": "09ec515e8daa6e5b914df85abb3618df",
  "date": "2016-09-13",
  "language": "ron",
  "media_urls": [
    "http://feedproxy.google.com/~r/romanian/~3/pKbuaH9oKNo/romanian_160913_554224.mp3",
    "http://mirror.widelanguageindex.org/ron/ron-09ec515e8daa6e5b914df85abb3618df.mp3"
  ],
  "source_name": "SBS Romanian",
  "source_url": "http://feedproxy.google.com/~r/romanian/~3/pKbuaH9oKNo/romanian_160913_554224.mp3",
  "title": "National Stroke Week"
}

=== ARLM-Keller/wide-language-index/index/mar/mar-23f767d3fd6b0cc2b499028f107c0a86.json
{
  "checksum": "23f767d3fd6b0cc2b499028f107c0a86",
  "date": "2016-09-14",
  "language": "mar",
  "media_urls": [
    "http://feedproxy.google.com/~r/MARPU_VOH/~3/bW7BV0qGaUw/MARPU_VOHX_20160914_4.mp3"
  ],
  "source_name": "AWR Marathi / Maharashtra / मराठी / Marāṭhī",
  "source_url": "http://feedproxy.google.com/~r/MARPU_VOH/~3/bW7BV0qGaUw/MARPU_VOHX_20160914_4.mp3",
  "title": "812) अडचणीमागे"
}
