=== ARLM-Keller/wide-language-index/index/sample.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Language sample",
    "description": "An audio sample tagged as containing a language of interest. It describes the sample's language, where it can be downloaded from, and its provenance.",
	"type": "object",
	"properties": {
		"language": {"type": "string"},
		"title": {"type": "string"},
		"source_name": {"type": "string"},
		"source_url": {"type": "string"},
		"media_urls": {
			"type": "array",
			"items": {
				"type": "string",
				"minItems": 1,
				"uniqueItems": true
			}
		},
		"checksum": {"type": "string"},
		"origin_checksum": {"type": "string"},
		"pregain": {"type": "string"},
		"date": {"type": "string"},
		"annotations": {
            "type": "array",
            "items": {"$ref": "annotation.schema.json"}
		}
	},
	"required": [
		"language",
		"title",
		"source_name",
		"source_url",
		"media_urls",
		"date",
		"checksum"
	]
}

=== ARLM-Keller/wide-language-index/index/prs/prs-93fdbe46600751ebf3a4f5afcc9b82da.json
{
  "checksum": "93fdbe46600751ebf3a4f5afcc9b82da",
  "date": "2013-08-10",
  "language": "prs",
  "media_urls": [
    "http://media.sbs.com.au/audio/persianfarsi_130810_282054.mp3",
    "http://mirror.widelanguageindex.org/prs/prs-93fdbe46600751ebf3a4f5afcc9b82da.mp3"
  ],
  "source_name": "SBS Persian-Farsi",
  "source_url": "http://www.sbs.com.au/yourlanguage/persian-farsi/highlight/page/id/282054/t/Profile-of-a-leader-Kevin-Rudd",
  "title": "\u062a\u0627\u0631\u06cc\u062e\u0686\u0647 \u0633\u06cc\u0627\u0633\u06cc \u06cc\u06a9 \u0631\u0647\u0628\u0631: \u06a9\u0648\u06cc\u0646 \u0631\u0627\u062f"
}

=== ARLM-Keller/wide-language-index/index/tir/tir-5e2cf884e52fd13b898d682200a30197.json
{
  "checksum": "5e2cf884e52fd13b898d682200a30197",
  "date": "2016-09-09",
  "language": "tir",
  "media_urls": [
    "http://feedproxy.google.com/~r/Tigrinya/~3/eBlm3sOyo8E/tigrinya_160910_553044.mp3",
    "http://mirror.widelanguageindex.org/tir/tir-5e2cf884e52fd13b898d682200a30197.mp3"
  ],
  "source_name": "SBS Tigrinya",
  "source_url": "http://feedproxy.google.com/~r/Tigrinya/~3/eBlm3sOyo8E/tigrinya_160910_553044.mp3",
  "title": "Eid Wishes"
}

=== ARLM-Keller/wide-language-index/index/tam/tam-8e5d5fcb21f53e699fa6df4758006142.json
{
  "checksum": "8e5d5fcb21f53e699fa6df4758006142",
  "date": "2012-11-06",
  "language": "tam",
  "media_urls": [
    "http://downloads.bbc.co.uk/podcasts/worldservice/tnmuslims/tnmuslims_20121106-1746a.mp3",
    "http://mirror.widelanguageindex.org/tam/tam-8e5d5fcb21f53e699fa6df4758006142.mp3"
  ],
  "source_name": "Tamil Nadu Muslims",
  "source_url": "http://downloads.bbc.co.uk/podcasts/worldservice/tnmuslims/tnmuslims_20121106-1746a.mp3",
  "title": "மீனாட்சிபுரம் இன்று"
}

=== ARLM-Keller/wide-language-index/index/lao/lao-b528bca4b4de117e76a10f29cb0b2527.json
{
  "checksum": "b528bca4b4de117e76a10f29cb0b2527",
  "date": "2016-09-16",
  "language": "lao",
  "media_urls": [
    "http://feedproxy.google.com/~r/lao/~3/lDcF15VJQLQ/laotian_160916_555742.mp3"
  ],
  "source_name": "SBS Lao",
  "source_url": "http://feedproxy.google.com/~r/lao/~3/lDcF15VJQLQ/laotian_160916_555742.mp3",
  "title": "Hong Kong Pro-democracy Wins Stunning Victory"
}

=== ARLM-Keller/wide-language-index/index/por/por-01b1e1990cc14361e0664bc3b5eb1422.json
{
  "checksum": "01b1e1990cc14361e0664bc3b5eb1422",
  "date": "2015-03-21",
  "language": "por",
  "media_urls": [
    "http://www3.nhk.or.jp/rj/podcast/mp3/20150322053100_1_portuguese.mp3"
  ],
  "source_name": "NHK World Radio Japan (Portuguese)",
  "source_url": "http://www3.nhk.or.jp/rj/podcast/mp3/20150322053100_1_portuguese.mp3",
  "title": "NHK WORLD RADIO JAPAN - Portuguese News at 05:31 (JST), March 22"
}

=== ARLM-Keller/wide-language-index/index/hat/hat-43153fd3263fd603df47b84bbe56305f.json
{
  "checksum": "43153fd3263fd603df47b84bbe56305f",
  "date": "2015-04-07",
  "language": "hat",
  "media_urls": [
    "http://av.voanews.com/clips/VCR/2015/04/07/20150407-163000-VCR-program.mp3",
    "http://mirror.widelanguageindex.org/hat/hat-43153fd3263fd603df47b84bbe56305f.mp3"
  ],
  "source_name": "Pwogram mitan jounen an - Lavwadlamerik",
  "source_url": "http://www.voanouvel.com/audio/2693215.html",
  "title": "Pwogram mitan jounen an - avril 07, 2015"
}

=== ARLM-Keller/wide-language-index/index/pol/pol-08a3cd7575e2737beca4fb26232ba68f.json
{
  "checksum": "08a3cd7575e2737beca4fb26232ba68f",
  "date": "2016-09-16",
  "language": "pol",
  "media_urls": [
    "http://feedproxy.google.com/~r/polish/~3/BrXUJonKsz8/polish_160916_555967.mp3"
  ],
  "source_name": "SBS Polish",
  "source_url": "http://feedproxy.google.com/~r/polish/~3/BrXUJonKsz8/polish_160916_555967.mp3",
  "title": "What will Happen to the Polish Club in Ashfield?"
}

=== ARLM-Keller/wide-language-index/index/fas/fas-3480653fe811feade90de16cd3db8db1.json
{
  "checksum": "3480653fe811feade90de16cd3db8db1",
  "date": "2015-03-22",
  "language": "fas",
  "media_urls": [
    "http://www3.nhk.or.jp/rj/podcast/mp3/20150322130100_1_persian.mp3"
  ],
  "source_name": "Persian News - NHK WORLD RADIO JAPAN",
  "source_url": "http://www3.nhk.or.jp/rj/podcast/mp3/20150322130100_1_persian.mp3",
  "title": "NHK WORLD RADIO JAPAN - Persian News at 13:01 (JST), March 22"
}
