=== ARLM-Keller/wide-language-index/index/sample.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Language sample",
    "description": "An audio sample tagged as containing a language of interest. It describes the sample's language, where it can be downloaded from, and its provenance.",
	"type": "object",
	"properties": {
		"language": {"type": "string"},
		"title": {"type": "string"},
		"source_name": {"type": "string"},
		"source_url": {"type": "string"},
		"media_urls": {
			"type": "array",
			"items": {
				"type": "string",
				"minItems": 1,
				"uniqueItems": true
			}
		},
		"checksum": {"type": "string"},
		"origin_checksum": {"type": "string"},
		"pregain": {"type": "string"},
		"date": {"type": "string"},
		"annotations": {
            "type": "array",
            "items": {"$ref": "annotation.schema.json"}
		}
	},
	"required": [
		"language",
		"title",
		"source_name",
		"source_url",
		"media_urls",
		"date",
		"checksum"
	]
}

=== ARLM-Keller/wide-language-index/index/swe/swe-715d6a3c2158025bcdd9cb0743256bb3.json
{
  "checksum": "715d6a3c2158025bcdd9cb0743256bb3",
  "date": "2016-09-16",
  "language": "swe",
  "media_urls": [
    "http://sverigesradio.se/topsy/ljudfil/5837821.mp3",
    "http://mirror.widelanguageindex.org/swe/swe-715d6a3c2158025bcdd9cb0743256bb3.mp3"
  ],
  "source_name": "Sveriges Radio - Ekot Nyheter",
  "source_url": "http://sverigesradio.se/sida/avsnitt/778892?programid=4540",
  "title": "Luncheko 20160916 12:30"
}

=== ARLM-Keller/wide-language-index/index/cmn/cmn-ee4cf4fb066e719cafd5a8de8f755726.json
{
  "checksum": "ee4cf4fb066e719cafd5a8de8f755726",
  "date": "2015-03-20",
  "language": "cmn",
  "media_urls": [
    "http://feedproxy.google.com/~r/radiomandarin/~3/UAg5tH3RiQ0/mandarin_150321_399700.mp3"
  ],
  "source_name": "SBS Australia",
  "source_url": "http://feedproxy.google.com/~r/radiomandarin/~3/UAg5tH3RiQ0/mandarin_150321_399700.mp3",
  "title": "Life Magazine\uff1aFiber vs Sugar"
}

=== ARLM-Keller/wide-language-index/index/por/por-4ee3cfff2c68ccb34cf35c42dfe37cf8.json
{
  "checksum": "4ee3cfff2c68ccb34cf35c42dfe37cf8",
  "date": "2015-03-18",
  "language": "por",
  "media_urls": [
    "http://rsspod.rtp.pt/podcasts/at1/1503/3463554_177030-1503161137.mp3",
    "http://mirror.widelanguageindex.org/por/por-4ee3cfff2c68ccb34cf35c42dfe37cf8.mp3"
  ],
  "source_name": "RTP: O Mundo ao Ouvido",
  "source_url": "http://rsspod.rtp.pt/podcasts/at1/1503/3463554_177030-1503161137.mp3",
  "title": "2015-03-18 07:45:00Pron√∫ncia do Norte"
}

=== ARLM-Keller/wide-language-index/index/epo/epo-c95245f0e415e18d0bd62f6acdc7d67a.json
{
  "annotations": [
    {
      "annotator": "Lars Yencken <lars@yencken.org>",
      "date": "2015-03-19",
      "duration": 20,
      "genders": "male",
      "label": "good",
      "offset": 680,
      "problems": [],
      "speakers": 1
    }
  ],
  "checksum": "c95245f0e415e18d0bd62f6acdc7d67a",
  "date": "2006-10-22",
  "language": "epo",
  "media_urls": [
    "http://www.archive.org/download/universal_declaration_librivox/human_rights_un_eo_ac.mp3"
  ],
  "source_name": "United Nations",
  "source_url": "https://librivox.org/the-universal-declaration-of-human-rights-by-the-united-nations/",
  "title": "Universal Declaration of Human Rights"
}

=== ARLM-Keller/wide-language-index/index/por/por-d39a06330f7dc205a23caad83e6cd2c3.json
{
  "checksum": "d39a06330f7dc205a23caad83e6cd2c3",
  "date": "2015-03-15",
  "language": "por",
  "media_urls": [
    "http://feedproxy.google.com/~r/portuguese/~3/txZwWzOF8G4/portuguese_150315_398402.mp3"
  ],
  "source_name": "SBS Portuguese",
  "source_url": "http://feedproxy.google.com/~r/portuguese/~3/txZwWzOF8G4/portuguese_150315_398402.mp3",
  "title": "Expectativas de Felipe Massa e Felipe Nasr no GP de F\u00f3rmula Um da Austr\u00e1lia"
}

=== ARLM-Keller/wide-language-index/index/nor/nor-580dffd3445cb8be8fb1a2ab7e819ece.json
{
  "checksum": "580dffd3445cb8be8fb1a2ab7e819ece",
  "date": "2015-11-13",
  "language": "nor",
  "media_urls": [
    "http://podkast.nrk.no/fil/dagsnytt/dagsnytt_2015-11-13_652_64.MP3?stat=1"
  ],
  "source_name": "NRK - Dagsnytt",
  "source_url": "http://podkast.nrk.no/fil/dagsnytt/dagsnytt_2015-11-13_652_64.MP3?stat=1",
  "title": "13.11.2015 Dagsnytt 0700"
}

=== ARLM-Keller/wide-language-index/index/spa/spa-2521759240da6147a88520696d734eb0.json
{
  "checksum": "2521759240da6147a88520696d734eb0",
  "date": "2009-08-01",
  "language": "spa",
  "media_urls": [
    "http://www.archive.org/download/human_rights_02_0908_librivox/human_rights_un_spa_mr.mp3"
  ],
  "source_name": "United Nations",
  "source_url": "https://librivox.org/universal-declaration-of-human-rights-by-united-nations-volume-02/",
  "title": "Universal Declaration of Human Rights"
}

=== ARLM-Keller/wide-language-index/index/tel/tel-49ce4178fadeb9d0ba77198fbd07e837.json
{
  "annotations": [
    {
      "annotator": "Lars Yencken <lars@yencken.org>",
      "date": "2015-04-12",
      "duration": 20,
      "genders": "mixed",
      "label": "bad",
      "offset": 2460,
      "problems": [
        "excess loan words",
        "pauses"
      ],
      "speakers": 2
    }
  ],
  "checksum": "49ce4178fadeb9d0ba77198fbd07e837",
  "date": "2013-08-30",
  "language": "tel",
  "media_urls": [
    "http://www.teluguoneradio.com/prgramdetails/20130830_subhashini_mmm.mp3",
    "http://mirror.widelanguageindex.org/tel/tel-49ce4178fadeb9d0ba77198fbd07e837.mp3"
  ],
  "source_name": "Telugu One Radio: Subhashini",
  "source_url": "http://www.teluguoneradio.com/archivesplayer.php?q=7822&host_id=62",
  "title": "Manalo Mana Maata"
}
